#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

redshift &

# feh --bg-center ~/Dropbox/壁纸/unsplash-Will\ Swann.jpg &
# feh --bg-fill ~/Dropbox/壁纸/kazetachinu050.jpg &
feh --bg-fill ~/Dropbox/壁纸/1451566265534_.pic_hd.jpg &

#xdpyinfo | grep -B2 resolution
#设置Xserver的dpi配置
xrandr --dpi 144

exec i3
